In [48]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import pandas as pd
import numpy as np

# Transforming World Development Indicators (WDI)

## current version

In [51]:
# loading up the data
WDI_full = pd.read_excel(r'data\raw\WDI_11_07_2025.xlsx')

In [52]:
# loading up the list of desired data
WDI_meta = ['CM.MKT.LCAP.CD'
            , 'CM.MKT.LCAP.GD.ZS'
            , 'CM.MKT.TRAD.CD'
            , 'CM.MKT.TRAD.GD.ZS'
            , 'FB.BNK.CAPA.ZS'
            , 'NY.GDP.MKTP.KD'
            , 'SP.POP.TOTL'
            , 'FS.AST.PRVT.GD.ZS'
            , 'NY.GDP.MKTP.PP.KD'
            ]

In [53]:
# # loading up the list of desired data
# WDI_meta = pd.read_excel(r'data\meta\WDI_meta.xlsx')['Series Code']

In [54]:
# taking the necescary data and turning into tablular data
WDI_full = WDI_full[WDI_full['Indicator Code'].isin(WDI_meta)]
WDI_full = pd.melt(WDI_full, id_vars=list(WDI_full.columns)[:4], value_vars=list(WDI_full.columns)[4:])

In [55]:
# renaming
WDI_full.rename(columns={'variable': 'Year'
                          , 'value': 'Value'
                         }
                 , inplace=True)

In [56]:
# making sure the data is an number
WDI_full['Value'] = pd.to_numeric(WDI_full['Value'], errors='coerce')

In [57]:
# taking only the necescary years
WDI_full['Year'] = WDI_full['Year'].astype(int)
WDI_full = WDI_full[WDI_full['Year']>1989]

In [58]:
WDI_full['Source']= 'World Bank 2025'

In [59]:
WDI_full = WDI_full.dropna(subset=['Value'])

## country name formatting

In [61]:
# making sure the names are propper
WDI_full['Country Name'].replace('Turkiye','Turkey',inplace=True)
WDI_full['Country Name'].replace('Egypt', 'Egypt, Arab Rep.',inplace=True)
WDI_full['Country Name'].replace('Russia','Russian Federation',inplace=True)
WDI_full['Country Name'].replace('''Côte d'Ivoire''','''Cote d'Ivoire''',inplace=True)
WDI_full['Country Name'].replace('Czechia','Czech Republic',inplace=True)
WDI_full['Country Name'].replace('Iran','Iran, Islamic Rep.',inplace=True)
WDI_full['Country Name'].replace('Korea','Korea, Rep.',inplace=True)
WDI_full['Country Name'].replace('Eswatini','Swaziland',inplace=True)
WDI_full['Country Name'].replace('Viet Nam','Vietnam',inplace=True)

In [62]:
WDI_full = WDI_full.drop_duplicates(subset=WDI_full.columns[:-2], keep='last')

# Combining the raw dfs

In [197]:
# loading up data from a previous study
WDI_GFDI_past_study = pd.read_excel(r'data\hand filled\WDI_GFDI_past_study.xlsx')

In [198]:
# loading up data from current study
WDI_GFDI_current_study = pd.read_excel(r'data\hand filled\WDI_GFDI_current_study.xlsx')

In [199]:
# everything together
WDI_full_everything = pd.concat([WDI_GFDI_past_study, WDI_GFDI_current_study, WDI_full])

In [200]:
# making sure the names are propper
WDI_full_everything['Country Name'].replace('Turkiye','Turkey',inplace=True)
WDI_full_everything['Country Name'].replace('Egypt', 'Egypt, Arab Rep.',inplace=True)
WDI_full_everything['Country Name'].replace('Russia','Russian Federation',inplace=True)
WDI_full_everything['Country Name'].replace('''Côte d'Ivoire''','''Cote d'Ivoire''',inplace=True)
WDI_full_everything['Country Name'].replace('Czechia','Czech Republic',inplace=True)
WDI_full_everything['Country Name'].replace('Iran','Iran, Islamic Rep.',inplace=True)
WDI_full_everything['Country Name'].replace('Korea','Korea, Rep.',inplace=True)
WDI_full_everything['Country Name'].replace('Eswatini','Swaziland',inplace=True)
WDI_full_everything['Country Name'].replace('Viet Nam','Vietnam',inplace=True)

In [201]:
WDI_full_everything = WDI_full_everything.dropna(subset=['Value'])

In [202]:
WDI_full_everything = WDI_full_everything[['Country Name'
                                           , 'Country Code'
                                           , 'Indicator Name'
                                           , 'Indicator Code'
                                           , 'Year'
                                           , 'Value'
                                           , 'Source'
                                          ]]

In [203]:
WDI_full_everything_WB = WDI_full_everything[WDI_full_everything['Source'].str.startswith('World Bank')].drop_duplicates(subset=['Country Name'
                                                                                                                    , 'Country Code'
                                                                                                                    , 'Indicator Name'
                                                                                                                    , 'Indicator Code'
                                                                                                                    , 'Year']
                                                                                                            , keep = 'last')

In [204]:
WDI_full_non_WB = WDI_full_everything[~WDI_full_everything['Source'].str.startswith('World Bank')].drop_duplicates(subset=['Country Name'
                                                                                                                    , 'Country Code'
                                                                                                                    , 'Indicator Name'
                                                                                                                    , 'Indicator Code'
                                                                                                                    , 'Year']
                                                                                                            , keep = 'last')

In [205]:
WDI_full = pd.concat([WDI_full_non_WB, WDI_full_everything_WB]).drop_duplicates(subset=['Country Name'
                                                                                        , 'Country Code'
                                                                                        , 'Indicator Name'
                                                                                        , 'Indicator Code'
                                                                                        , 'Year']
                                                                                , keep = 'last')

In [206]:
WDI_full

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Value,Source
960,Brazil,BRA,Market capitalization of listed domestic compa...,CM.MKT.LCAP.CD,1990,1.640000e+10,tradingeconomics - Brazil - Market Capitalizat...
961,Brazil,BRA,Market capitalization of listed domestic compa...,CM.MKT.LCAP.CD,1991,4.280000e+10,tradingeconomics - Brazil - Market Capitalizat...
962,Brazil,BRA,Market capitalization of listed domestic compa...,CM.MKT.LCAP.CD,1992,4.530000e+10,tradingeconomics - Brazil - Market Capitalizat...
963,Brazil,BRA,Market capitalization of listed domestic compa...,CM.MKT.LCAP.CD,1993,9.940000e+10,tradingeconomics - Brazil - Market Capitalizat...
964,Brazil,BRA,Market capitalization of listed domestic compa...,CM.MKT.LCAP.CD,1994,1.890000e+11,tradingeconomics - Brazil - Market Capitalizat...
...,...,...,...,...,...,...,...
126934,Zambia,ZMB,"Stocks traded, total value (% of GDP)",CM.MKT.TRAD.GD.ZS,2024,5.496514e-02,World Bank 2025
126935,Zambia,ZMB,"Stocks traded, total value (current US$)",CM.MKT.TRAD.CD,2024,1.447000e+07,World Bank 2025
126938,Zimbabwe,ZWE,GDP (constant 2015 US$),NY.GDP.MKTP.KD,2024,2.363417e+10,World Bank 2025
126939,Zimbabwe,ZWE,"GDP, PPP (constant 2021 international $)",NY.GDP.MKTP.PP.KD,2024,5.739074e+10,World Bank 2025
126942,Zimbabwe,ZWE,"Population, total",SP.POP.TOTL,2024,1.663437e+07,World Bank 2025

In [207]:
# a piovt table to see how many entries of each variable
wdi_piovt = WDI_full.pivot_table(index=['Country Code'],
                                 columns=['Indicator Name'],
                                 values=['Value'],
                                 aggfunc='count')#.to_excel(r'wdi_piovt.xlsx')

In [208]:
# if a country has less than 8 entries set as none and drop those
wdi_piovt = wdi_piovt.applymap(lambda x: None if x < 8 else x).dropna()

In [209]:
# and thus we get a list of countries which have at least 8 entries of each variable
country_codes = list(wdi_piovt.index.get_level_values(0))

In [210]:
len(country_codes)

55

In [211]:
WDI_full_target = WDI_full[WDI_full['Country Code'].isin(country_codes)]

In [212]:
WDI_full_target

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Value,Source
960,Brazil,BRA,Market capitalization of listed domestic compa...,CM.MKT.LCAP.CD,1990,1.640000e+10,tradingeconomics - Brazil - Market Capitalizat...
961,Brazil,BRA,Market capitalization of listed domestic compa...,CM.MKT.LCAP.CD,1991,4.280000e+10,tradingeconomics - Brazil - Market Capitalizat...
962,Brazil,BRA,Market capitalization of listed domestic compa...,CM.MKT.LCAP.CD,1992,4.530000e+10,tradingeconomics - Brazil - Market Capitalizat...
963,Brazil,BRA,Market capitalization of listed domestic compa...,CM.MKT.LCAP.CD,1993,9.940000e+10,tradingeconomics - Brazil - Market Capitalizat...
964,Brazil,BRA,Market capitalization of listed domestic compa...,CM.MKT.LCAP.CD,1994,1.890000e+11,tradingeconomics - Brazil - Market Capitalizat...
...,...,...,...,...,...,...,...
126931,Zambia,ZMB,Market capitalization of listed domestic compa...,CM.MKT.LCAP.GD.ZS,2024,2.949630e+01,World Bank 2025
126932,Zambia,ZMB,Market capitalization of listed domestic compa...,CM.MKT.LCAP.CD,2024,7.765130e+09,World Bank 2025
126933,Zambia,ZMB,"Population, total",SP.POP.TOTL,2024,2.131496e+07,World Bank 2025
126934,Zambia,ZMB,"Stocks traded, total value (% of GDP)",CM.MKT.TRAD.GD.ZS,2024,5.496514e-02,World Bank 2025
126935,Zambia,ZMB,"Stocks traded, total value (current US$)",CM.MKT.TRAD.CD,2024,1.447000e+07,World Bank 2025

In [213]:
# # bringing in extra info about the countries (their region and income groups
# WDI_full_target = pd.merge(WDI_full_target, GFDI_country, how='left', on='Country Code')

In [214]:
# # reoredring the columns
# WDI_full_target = WDI_full_target[['Country Name'
#                                    , 'Country Code'
#                                    , 'region'
#                                    , 'income'
#                                    , 'Indicator Name'
#                                    , 'Indicator Code'
#                                    , 'Year'
#                                    , 'Value'


#                                    ,'Source'
#                                   ]]

# adding the hand collected data to the filtered raw df

In [216]:
target_columns = ['Bank deposits to GDP (%)'
                  , 'Domestic credit to private sector (% of GDP)'
                  # , 'Broad money (% of GDP)'
                  , 'Stocks traded, total value (% of GDP)'
                  , 'Market capitalization of listed domestic companies (% of GDP)'
                  , 'GDP (constant 2015 US$)'
                  # , 'GDP (current US$)'
                  # , 'GDP per capita, PPP (constant 2021 international $)'
                  # , 'GDP, PPP (constant 2021 international $)'
                 ]

In [217]:
WDI_full_target = WDI_full_target[WDI_full_target['Indicator Name'].isin(target_columns)]

In [218]:
WDI_full_target

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Value,Source
1088,Chile,CHL,Domestic credit to private sector (% of GDP),FS.AST.PRVT.GD.ZS,1990,4.317874e+01,tradingeconomics - Chile - Domestic Credit To ...
1089,Chile,CHL,Domestic credit to private sector (% of GDP),FS.AST.PRVT.GD.ZS,1991,4.105306e+01,tradingeconomics - Chile - Domestic Credit To ...
1090,Chile,CHL,Domestic credit to private sector (% of GDP),FS.AST.PRVT.GD.ZS,1992,4.373411e+01,tradingeconomics - Chile - Domestic Credit To ...
1091,Chile,CHL,Domestic credit to private sector (% of GDP),FS.AST.PRVT.GD.ZS,1993,4.763746e+01,tradingeconomics - Chile - Domestic Credit To ...
1092,Chile,CHL,Domestic credit to private sector (% of GDP),FS.AST.PRVT.GD.ZS,1994,4.651072e+01,tradingeconomics - Chile - Domestic Credit To ...
...,...,...,...,...,...,...,...
126913,West Bank and Gaza,PSE,Market capitalization of listed domestic compa...,CM.MKT.LCAP.GD.ZS,2024,2.975735e+01,World Bank 2025
126916,West Bank and Gaza,PSE,"Stocks traded, total value (% of GDP)",CM.MKT.TRAD.GD.ZS,2024,1.197497e+00,World Bank 2025
126929,Zambia,ZMB,GDP (constant 2015 US$),NY.GDP.MKTP.KD,2024,2.869582e+10,World Bank 2025
126931,Zambia,ZMB,Market capitalization of listed domestic compa...,CM.MKT.LCAP.GD.ZS,2024,2.949630e+01,World Bank 2025
126934,Zambia,ZMB,"Stocks traded, total value (% of GDP)",CM.MKT.TRAD.GD.ZS,2024,5.496514e-02,World Bank 2025

In [240]:
target_columns = ['Poland'
                  , 'Mauritius'
                  , 'Thailand'
                  , 'Australia'
                  , 'Nigeria'
                  , 'Brazil'
                  , 'Singapore'
                  , 'Chile'
                  , 'United States'
                  , 'China'
                  , 'Mexico'
                  , 'Hong Kong SAR, China'
                  , 'Philippines'
                  , 'India'
                  , 'Russian Federation'
                  , 'Indonesia'
                  , 'South Africa'
                  , 'Israel'
                  , 'Turkey'
                  , 'Japan'
                  , 'Korea, Rep.'
                  , 'Malaysia'
                 ]

In [244]:
WDI_full_target[WDI_full_target['Country Name'].isin(target_columns)].to_excel(r'data\WDI_full_collected.xlsx', index=False)

In [126]:
# loading up data from a previous study
WDI_full_target.to_excel(r'data\WDI_full_collected.xlsx', index=False)